#!/usr/bin/env bash
# Concatenate the numbered migrations into one file you can paste into the
# Supabase SQL editor in a single go. Regenerate with `npm run db:bundle`.
set -euo pipefail

cd "$(dirname "$0")/.."
out=supabase/setup.sql

{
  echo "-- GENERATED by scripts/bundle-migrations.sh — do not edit by hand."
  echo "-- Source of truth is supabase/migrations/*.sql. Run this whole file"
  echo "-- once, in order, in the Supabase SQL editor."
  echo
  for f in supabase/migrations/*.sql; do
    echo
    echo "-- ======================== $(basename "$f") ========================"
    echo
    cat "$f"
  done
} > "$out"

echo "Wrote $out ($(wc -l < "$out" | tr -d ' ') lines)"
