#!/usr/bin/env bash
# Concatenate the shared migrations into one file you can paste into the
# Supabase SQL editor. Regenerate with `npm run db:bundle`.
#
# Files ending in _local.sql are skipped: those hold real email addresses or
# other per-project bootstrap data, they are gitignored, and this output is
# committed to a public repository.
set -euo pipefail

cd "$(dirname "$0")/.."
out=supabase/setup.sql

{
  echo "-- GENERATED by scripts/bundle-migrations.sh — do not edit by hand."
  echo "-- Source of truth is supabase/migrations/*.sql. Safe to re-run: every"
  echo "-- statement is idempotent."
  echo
  for f in supabase/migrations/*.sql; do
    case "$f" in
      *_local.sql) echo "-- (skipped $(basename "$f") — local bootstrap, not shared)" ; continue ;;
    esac
    echo
    echo "-- ======================== $(basename "$f") ========================"
    echo
    cat "$f"
  done
} > "$out"

# Belt and braces: never ship a bundle containing a real address.
leaked=$(grep -oE '[[:alnum:]._%+-]+@[[:alnum:].-]+\.[a-z]{2,}' "$out" | grep -v '@example\.com' || true)
if [ -n "$leaked" ]; then
  echo "ERROR: $out contains real email addresses:" >&2
  echo "$leaked" >&2
  exit 1
fi

echo "Wrote $out ($(wc -l < "$out" | tr -d ' ') lines)"
